import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import type { Appointment, Dashboard } from "@bookwise/shared";

const apiUrl = process.env.EXPO_PUBLIC_API_URL ?? "http://localhost:4000/api";
const fallback: Dashboard = { businessName: "光嶼顧問工作室", todayAppointments: 3, monthlyRevenue: 128400, occupancyRate: 78, appointments: [
  { id: "1", customerName: "林怡君", service: "初次諮詢", startsAt: "2026-09-25T10:00:00+08:00", durationMinutes: 60, status: "confirmed" },
  { id: "2", customerName: "陳柏翰", service: "品牌策略工作坊", startsAt: "2026-09-25T13:30:00+08:00", durationMinutes: 90, status: "pending" },
] };
const time = (value: string) => new Date(value).toLocaleTimeString("zh-TW", { hour: "2-digit", minute: "2-digit", hour12: false });

export default function Home() {
  const [dashboard, setDashboard] = useState(fallback);
  useEffect(() => { fetch(`${apiUrl}/v1/dashboard`).then((response) => response.json()).then((result) => setDashboard(result.data)).catch(() => undefined); }, []);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><View style={styles.top}><View><Text style={styles.kicker}>BOOKWISE / 今日</Text><Text style={styles.title}>早安，光嶼團隊</Text></View><View style={styles.logo}><Text style={styles.logoText}>B</Text></View></View><View style={styles.hero}><Text style={styles.heroKicker}>今日工作台</Text><Text style={styles.heroTitle}>把重要的會面，{`\n`}留給重要的人。</Text><Text style={styles.heroText}>所有預約都在這裡清楚掌握。</Text><Pressable style={styles.primary}><Ionicons name="add" color="#fff" size={18} /><Text style={styles.primaryText}>新增預約</Text></Pressable></View><View style={styles.cards}><Stat icon={<Ionicons name="calendar-outline" color="#197d68" size={18} />} label="今日預約" value={String(dashboard.todayAppointments)} /><Stat icon={<Ionicons name="people-outline" color="#197d68" size={18} />} label="本月營收" value={`$${Math.round(dashboard.monthlyRevenue / 1000)}k`} /><Stat icon={<Ionicons name="time-outline" color="#197d68" size={18} />} label="使用率" value={`${dashboard.occupancyRate}%`} /></View><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>今日行程</Text><Text style={styles.link}>查看全部</Text></View>{dashboard.appointments.map((appointment) => <AppointmentCard key={appointment.id} appointment={appointment} />)}<View style={styles.tip}><Text style={styles.tipMark}>↗</Text><Text style={styles.tipText}>本月回訪率比上個月高出 18%。</Text></View></ScrollView></SafeAreaView>;
}
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <View style={styles.stat}><View style={styles.statIcon}>{icon}</View><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View>; }
function AppointmentCard({ appointment }: { appointment: Appointment }) { return <View style={styles.appointment}><View style={styles.time}><Text style={styles.timeText}>{time(appointment.startsAt)}</Text><Text style={styles.duration}>{appointment.durationMinutes} min</Text></View><View style={styles.detail}><View style={styles.customer}><Text style={styles.customerText}>{appointment.customerName.slice(0, 1)}</Text></View><View><Text style={styles.customerName}>{appointment.customerName}</Text><Text style={styles.service}>{appointment.service}</Text></View></View><Ionicons name="chevron-forward" color="#aab5af" size={17} /></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#f6f7f5" }, container: { padding: 22, paddingBottom: 45 }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, kicker: { color: "#9aa7a1", fontSize: 10, letterSpacing: 1.4, marginBottom: 7 }, title: { color: "#172126", fontSize: 23, fontWeight: "700" }, logo: { width: 39, height: 39, borderRadius: 12, backgroundColor: "#197d68", justifyContent: "center", alignItems: "center" }, logoText: { color: "#fff", fontSize: 19, fontWeight: "700" }, hero: { marginTop: 39, padding: 21, borderRadius: 14, backgroundColor: "#dff1e9" }, heroKicker: { color: "#24816b", fontSize: 11, fontWeight: "700" }, heroTitle: { color: "#172126", fontSize: 28, lineHeight: 35, fontWeight: "800", marginTop: 13 }, heroText: { color: "#6f8178", fontSize: 12, marginTop: 10 }, primary: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 7, paddingVertical: 11, paddingHorizontal: 14, borderRadius: 7, marginTop: 19, backgroundColor: "#197d68" }, primaryText: { color: "#fff", fontSize: 12, fontWeight: "700" }, cards: { flexDirection: "row", gap: 8, marginTop: 15 }, stat: { flex: 1, minHeight: 104, padding: 11, borderRadius: 10, backgroundColor: "#fff", borderWidth: 1, borderColor: "#e6ebe7" }, statIcon: { width: 29, height: 29, borderRadius: 8, justifyContent: "center", alignItems: "center", backgroundColor: "#e4f4ee" }, statLabel: { color: "#9aa7a1", fontSize: 10, marginTop: 10 }, statValue: { color: "#172126", fontSize: 20, fontWeight: "700", marginTop: 5 }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 31, marginBottom: 12 }, sectionTitle: { color: "#172126", fontSize: 19, fontWeight: "700" }, link: { color: "#25836e", fontSize: 11 }, appointment: { minHeight: 80, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 15, borderRadius: 10, marginBottom: 8, backgroundColor: "#fff", borderWidth: 1, borderColor: "#e6ebe7" }, time: { width: 49 }, timeText: { color: "#172126", fontSize: 14, fontWeight: "700" }, duration: { color: "#a4aea9", fontSize: 9, marginTop: 4 }, detail: { flex: 1, flexDirection: "row", alignItems: "center", gap: 9 }, customer: { width: 32, height: 32, borderRadius: 16, justifyContent: "center", alignItems: "center", backgroundColor: "#f5e4d9" }, customerText: { color: "#8f5e47", fontSize: 12, fontWeight: "700" }, customerName: { color: "#172126", fontSize: 12, fontWeight: "700" }, service: { color: "#9aa7a1", fontSize: 10, marginTop: 4 }, tip: { flexDirection: "row", alignItems: "center", gap: 10, padding: 14, marginTop: 17, borderRadius: 8, backgroundColor: "#e6f5ed" }, tipMark: { color: "#21836d", fontSize: 19 }, tipText: { color: "#477166", fontSize: 11 } });